##Text Vectorization

In [2]:
import pandas as pd
import numpy as np
import pickle
import os



from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
movies = pd.read_csv("processed_movies.csv")

In [4]:
print(movies.shape)
print(movies.columns)
print(movies["tags"].isnull().sum())

(44479, 3)
Index(['id', 'title', 'tags'], dtype='str')
0

In [5]:
cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

In [6]:
vectors = cv.fit_transform(movies['tags'])

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(movie):
    
    movie_data = movies[
        movies["title"].str.lower() == movie.lower()
    ]

    if movie_data.empty:
        print("Movie not found!")
        return

    movie_index = movie_data.index[0]

    # Calculate similarity only for this movie
    distances = cosine_similarity(
        vectors[movie_index],
        vectors
    ).flatten()

    movie_list = list(enumerate(distances))

    movie_list = sorted(
        movie_list,
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    print(f"\nRecommendations for '{movie}':\n")

    for i, score in movie_list:
        print(movies.iloc[i]["title"])

In [8]:
print("Vectors shape:", vectors.shape)

Vectors shape: (44479, 5000)

In [9]:
recommend("Interstellar")

Recommendations for 'Interstellar':

Journey to the Seventh Planet
Manhunt in Space
Space Warriors
SpaceCamp
Space Station 3D

In [10]:
stop_words='english'

In [11]:
cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(movies['tags']).toarray()

In [12]:
vectors.shape

(44479, 5000)

In [43]:
similarity.shape

(44479, 44479)

In [15]:
movies[movies['title'] == 'Interstellar']

           id         title                                               tags
22678  157336  Interstellar  Interstellar chronicles the adventures of a gr...

In [16]:
movies[movies['title'].str.contains('Inter', case=False, na=False)]

,id,title,tags
93,40154,A Midwinter's Tale,Out of work actor Joe volunteers to help try a...
248,628,Interview with the Vampire,"A vampire relates his epic life story of love,..."
671,40001,Mrs. Winterbourne,Connie Doyle is eighteen and pregnant her boyf...
1435,816,Austin Powers: International Man of Mystery,As a swingin' fashion photographer by day and ...
1629,25994,The Winter Guest,The plot of the story is interactions between ...
...,...,...,...
43498,83524,Intergirl,"A hospital nurse becomes an ""international gir..."
43514,64278,Interceptor Force 2,In the not too distant future a new team of sp...
43621,72811,Winter Cherries,A story about a difficult love between the two...
43810,461805,The Putin Interviews,"Academy Award-winning filmmaker, Oliver Stone ..."
43865,26539,Frosty's Winter Wonderland,Years have passed since Frosty left for the No...

In [17]:
movies['title'].head(20)

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3                  Waiting to Exhale
4        Father of the Bride Part II
5                               Heat
6                            Sabrina
7                       Tom and Huck
8                       Sudden Death
9                          GoldenEye
10            The American President
11       Dracula: Dead and Loving It
12                             Balto
13                             Nixon
14                  Cutthroat Island
15                            Casino
16             Sense and Sensibility
17                        Four Rooms
18    Ace Ventura: When Nature Calls
19                       Money Train
Name: title, dtype: str

In [18]:
movies.shape

(44479, 3)

In [19]:
vectors.shape

(44479, 5000)

In [41]:
similarity = cosine_similarity(vectors)

print(similarity.shape)

(44479, 44479)

In [42]:
movies[movies['title'] == 'Heat']

          id title                                               tags
5        949  Heat  Obsessive master thief, Neil McCauley leads a ...
14623   4579  Heat  Former child star Joe Davis (Joe Dallesandro),...
28715  42023  Heat  Reynolds plays an ex-soldier-of-fortunish char...

In [21]:



def recommend(movie):
    
    # Find movie index
    movie_index = movies[movies['title'] == movie].index[0]

    # Get similarity scores
    distances = similarity[movie_index]

    # Pair movie index with similarity score
    movie_list = list(enumerate(distances))

    # Sort by similarity (highest first)
    movie_list = sorted(movie_list, key=lambda x: x[1], reverse=True)

    # Skip the first movie (it's the same movie)
    movie_list = movie_list[1:6]

    # Print recommendations
    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [22]:
movies['title'].sample(20)

10139                               At the Circus
2302                            Down in the Delta
20031                            English Vinglish
33707                          The Devil's Needle
18786                              3rd World Hero
200                 Under Siege 2: Dark Territory
23643                                 The Suspect
23028                               The Reckoning
13377                                  Ralliraita
40878                                   Automatic
34765                           The Man I Married
13225                              High and Dizzy
38404                                        Prey
24745                                Last Weekend
2783                     Ferris Bueller's Day Off
40251                       Sense and Sensibility
32403                       Would I Lie to You? 2
21876                               Caught Inside
26880    The Adventures of Tom Thumb & Thumbelina
7757                              To Each His Own
Name: title, dtype: str

In [23]:
def recommend(movie):
    movie_data = movies[movies['title'].str.lower() == movie.lower()]

    if movie_data.empty:
        print("Movie not found!")
        return

    movie_index = movie_data.index[0]

    distances = similarity[movie_index]

    movie_list = list(enumerate(distances))

    movie_list = sorted(movie_list, key=lambda x: x[1], reverse=True)[1:6]

    print(f"\nRecommendations for '{movie}':\n")

    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [24]:
import pickle

pickle.dump(
    movies,
    open("movies.pkl", "wb")
)

In [25]:
import pandas as pd
import numpy as np
import pickle

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
import os

print(os.getcwd())

c:\projects\movie-recommendations-system\notebooks

In [27]:
print(os.listdir())

['02_recommendation_engine.ipynb', '1-data_overview.ipynb', 'movies.pkl', 'processed_movies.csv']

In [28]:
movies = pd.read_csv("processed_movies.csv")

In [29]:
movies.head()

,id,title,tags
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...

In [30]:
movies.columns

Index(['id', 'title', 'tags'], dtype='str')

In [31]:
movies["tags"].isnull().sum()

np.int64(0)

In [32]:
cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors = cv.fit_transform(movies["tags"])

In [47]:
print(vectors.shape)

(44479, 5000)

In [48]:
print(similarity.shape)

(44479, 44479)

In [49]:
pickle.dump(
    movies,
    open("movies.pkl", "wb")
)

In [50]:
print(movies.shape)
print(similarity.shape)

(44479, 3)
(44479, 44479)

In [51]:
print(similarity.dtype)
print(similarity.nbytes / (1024 ** 3), "GB")

float64
14.740090377628803 GB

In [59]:
print(vectors.shape)

(44479, 5000)

In [60]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(
    metric="cosine",
    algorithm="brute"
)

nn.fit(vectors)

print("NearestNeighbors model fitted successfully!")

NearestNeighbors model fitted successfully!

In [66]:
distances, indices = nn.kneighbors(
    vectors[0],
    n_neighbors=21
)

In [69]:
distances, indices = nn.kneighbors(vectors[0], n_neighbors=21)

In [70]:
recommendation_indices = indices[:, 1:]

In [71]:
print(recommendation_indices.shape)

(1, 20)

In [73]:
for i in indices[0]:
    print(movies.iloc[i]["title"])

Toy Story
Toy Story 3
Toy Story 2
The 40 Year Old Virgin
The Champ
Andy Kaufman Plays Carnegie Hall
Andy Peters: Exclamation Mark Question Point
Andy Hardy's Blonde Trouble
You're Only Young Once
Partysaurus Rex
Andy Hardy's Private Secretary
Bobik Visiting Barbos
In a Heartbeat
Ready? OK!
Life Begins for Andy Hardy
A Family Affair
Group Sex
Wabash Avenue
Andy Hardy's Double Life
Gena the Crocodile
Banana

In [74]:
def recommend(movie):

    movie_data = movies[
        movies["title"].str.lower() == movie.lower()
    ]

    if movie_data.empty:
        print("Movie not found!")
        return

    movie_index = movie_data.index[0]

    distances, indices = nn.kneighbors(
        vectors[movie_index],
        n_neighbors=6
    )

    print(f"\nRecommendations for '{movie}':\n")

    for i in indices[0][1:]:
        print(movies.iloc[i]["title"])

In [76]:
recommend("Interstellar")

Recommendations for 'Interstellar':

Journey to the Seventh Planet
Manhunt in Space
Space Warriors
SpaceCamp
Space Station 3D

In [75]:
recommendations = {}

for i in range(len(movies)):
    recommendations[i] = recommendation_indices[i].tolist()

IndexError: index 1 is out of bounds for axis 0 with size 1

In [77]:
print(len(recommendations))

1

In [ ]:
movie_index = 0

print("Movie:", movies.iloc[movie_index]["title"])

print("\nRecommended movies:")

for index in recommendations[movie_index]:
    print(movies.iloc[index]["title"])

Movie: Toy Story

Recommended movies:
Toy Story 3
Toy Story 2
The 40 Year Old Virgin
The Champ
Andy Kaufman Plays Carnegie Hall
Andy Peters: Exclamation Mark Question Point
Andy Hardy's Blonde Trouble
You're Only Young Once
Partysaurus Rex
Andy Hardy's Private Secretary
Bobik Visiting Barbos
In a Heartbeat
Ready? OK!
Life Begins for Andy Hardy
A Family Affair
Group Sex
Wabash Avenue
Andy Hardy's Double Life
Gena the Crocodile
Banana

In [78]:
import pickle

with open("recommendations.pkl", "wb") as f:
    pickle.dump(recommendations, f)

In [79]:
import os

size = os.path.getsize("recommendations.pkl") / (1024 ** 2)

print(f"File size: {size:.2f} MB")

File size: 0.00 MB

In [80]:
with open("recommendations.pkl", "rb") as f:
    loaded_recommendations = pickle.load(f)

In [81]:
print(len(loaded_recommendations))

1

In [82]:
def recommend(movie):
    movie = movie.lower()

    matches = movies[
        movies["title"].str.lower() == movie
    ]

    if matches.empty:
        return []

    movie_index = matches.index[0]

    recommended_indices = recommendations[movie_index]

    return movies.iloc[recommended_indices]["title"].tolist()

In [83]:
recommend("Toy Story")

['Toy Story 3',
 'Toy Story 2',
 'The 40 Year Old Virgin',
 'The Champ',
 'Andy Kaufman Plays Carnegie Hall',
 'Andy Peters: Exclamation Mark Question Point',
 "Andy Hardy's Blonde Trouble",
 "You're Only Young Once",
 'Partysaurus Rex',
 "Andy Hardy's Private Secretary",
 'Bobik Visiting Barbos',
 'In a Heartbeat',
 'Ready? OK!',
 'Life Begins for Andy Hardy',
 'A Family Affair',
 'Group Sex',
 'Wabash Avenue',
 "Andy Hardy's Double Life",
 'Gena the Crocodile',
 'Banana']

In [84]:
for movie in recommend("Toy Story"):
    print(movie)

Toy Story 3
Toy Story 2
The 40 Year Old Virgin
The Champ
Andy Kaufman Plays Carnegie Hall
Andy Peters: Exclamation Mark Question Point
Andy Hardy's Blonde Trouble
You're Only Young Once
Partysaurus Rex
Andy Hardy's Private Secretary
Bobik Visiting Barbos
In a Heartbeat
Ready? OK!
Life Begins for Andy Hardy
A Family Affair
Group Sex
Wabash Avenue
Andy Hardy's Double Life
Gena the Crocodile
Banana

In [86]:
movie_id_to_index = pd.Series(
    movies.index,
    index=movies["id"]
).to_dict()

In [87]:
print(list(movie_id_to_index.items())[:5])

[(862, 0), (8844, 1), (15602, 2), (31357, 3), (11862, 4)]

In [88]:
def recommend(movie):
    matches = movies[
        movies["title"].str.lower() == movie.lower()
    ]

    if matches.empty:
        return []

    movie_index = matches.index[0]

    recommended_indices = recommendations[movie_index]

    result = []

    for index in recommended_indices:
        result.append(movies.iloc[index]["title"])

    return result

In [89]:
recommend("Toy Story")

['Toy Story 3',
 'Toy Story 2',
 'The 40 Year Old Virgin',
 'The Champ',
 'Andy Kaufman Plays Carnegie Hall',
 'Andy Peters: Exclamation Mark Question Point',
 "Andy Hardy's Blonde Trouble",
 "You're Only Young Once",
 'Partysaurus Rex',
 "Andy Hardy's Private Secretary",
 'Bobik Visiting Barbos',
 'In a Heartbeat',
 'Ready? OK!',
 'Life Begins for Andy Hardy',
 'A Family Affair',
 'Group Sex',
 'Wabash Avenue',
 "Andy Hardy's Double Life",
 'Gena the Crocodile',
 'Banana']

In [90]:
for movie in recommend("Toy Story"):
    print(movie)

Toy Story 3
Toy Story 2
The 40 Year Old Virgin
The Champ
Andy Kaufman Plays Carnegie Hall
Andy Peters: Exclamation Mark Question Point
Andy Hardy's Blonde Trouble
You're Only Young Once
Partysaurus Rex
Andy Hardy's Private Secretary
Bobik Visiting Barbos
In a Heartbeat
Ready? OK!
Life Begins for Andy Hardy
A Family Affair
Group Sex
Wabash Avenue
Andy Hardy's Double Life
Gena the Crocodile
Banana

In [93]:
movies.to_pickle("movies.pkl")

In [94]:
os.path.getsize("movies.pkl") / (1024 ** 2)

19.437719345092773

In [1]:
import requests

poster_path = toy.iloc[0]["poster_path"]

url = f"https://image.tmdb.org/t/p/w500{poster_path}"

response = requests.get(url)

print("URL:", url)
print("Status:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))

NameError: name 'toy' is not defined

In [2]:
import pandas as pd

movie_details = pd.read_pickle("../data/movie_details.pkl")

toy = movie_details[
    movie_details["title"].str.lower() == "toy story"
]

print(
    toy[["id", "title", "poster_path"]].to_string(index=False)
)

 id     title                      poster_path
862 Toy Story /rhIRbceoE9lR4veEXuwCC2wARtG.jpg