## data understanding

In [107]:

import pandas as pd
import numpy as np
import ast

In [ ]:
movies = pd.read_csv("../movies_metadata.csv", low_memory=False)

credits = pd.read_csv("../credits.csv")

keywords = pd.read_csv("../keywords.csv")

ratings = pd.read_csv("../ratings_small.csv")

In [ ]:
movies.sample(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
11412,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,21600,tt0033740,en,I Wake Up Screaming,A young promoter (Mature) is accused of the mu...,...,1941-10-31,0.0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,I Wake Up Screaming,False,4.8,8.0
41740,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",http://kylekinane.vhx.tv/,320892,tt3973036,en,Kyle Kinane: I Liked His Old Stuff Better,"Filmed at the historic 40 Watt Club in Athens,...",...,2015-01-23,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Kyle Kinane: I Liked His Old Stuff Better,False,9.0,2.0
42600,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 27, 'name...",NaN,423246,tt4655630,en,Drifter,A pair of outlaw brothers seek temporary refug...,...,2016-10-19,0.0,86.0,[],Released,Live in fear.,Drifter,False,6.7,3.0
1005,False,"{'id': 355490, 'name': 'Freeway Collection', '...",3000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,11229,tt0116361,en,Freeway,"Following the arrest of her mother, Ramona, yo...",...,1996-08-23,0.0,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Her life is no fairy tale.,Freeway,False,6.5,95.0
27091,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",NaN,144475,tt0024958,en,The Case of the Howling Dog,A very nervous man named Cartwright comes into...,...,1934-09-22,0.0,74.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Case of the Howling Dog,False,7.3,2.0

In [ ]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  str
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(1), str(19)
memory usage: 8.3+ MB

In [ ]:
movies.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [ ]:
movies = movies[
    [
        "id",
        "title",
        "overview",
        "genres",
        "release_date",
        "vote_average",
        "vote_count",
        "popularity"
    ]
]

In [ ]:
movies = movies.dropna(subset=["overview"])

In [ ]:
movies = movies.fillna("")

In [ ]:
movies = movies[pd.to_numeric(movies["id"], errors="coerce").notnull()]

movies["id"] = movies["id"].astype(int)

In [ ]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [ ]:
credits["id"] = credits["id"].astype(int)

In [ ]:
keywords["id"] = keywords["id"].astype(int)

In [ ]:
movies = movies.merge(credits, on="id")

movies = movies.merge(keywords, on="id")

In [ ]:
movies["genres"] = movies["genres"].apply(ast.literal_eval)

movies["cast"] = movies["cast"].apply(ast.literal_eval)

movies["crew"] = movies["crew"].apply(ast.literal_eval)

movies["keywords"] = movies["keywords"].apply(ast.literal_eval)

In [ ]:
movies.head()

,id,title,overview,genres,release_date,vote_average,vote_count,popularity,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",1995-10-30,7.7,5415.0,21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",1995-12-15,6.9,2413.0,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",1995-12-22,6.5,92.0,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-12-22,6.1,34.0,3.859495,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",1995-02-10,5.7,173.0,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [ ]:
def convert(obj):
    L = []

    for i in obj:
        L.append(i['name'])

    return L

In [ ]:
movies['genres'] = movies['genres'].apply(convert)

In [ ]:
movies.head()

,id,title,overview,genres,release_date,vote_average,vote_count,popularity,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]",1995-10-30,7.7,5415.0,21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]",1995-12-15,6.9,2413.0,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]",1995-12-22,6.5,92.0,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]",1995-12-22,6.1,34.0,3.859495,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],1995-02-10,5.7,173.0,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)

In [ ]:
def convert_cast(obj):

    L = []

    counter = 0

    for i in obj:

        if counter != 3:

            L.append(i['name'])

            counter += 1

        else:

            break

    return L


movies['cast'] = movies['cast'].apply(convert_cast)

In [ ]:
movies.head()

,id,title,overview,genres,release_date,vote_average,vote_count,popularity,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]",1995-10-30,7.7,5415.0,21.946943,"[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]",1995-12-15,6.9,2413.0,17.015539,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]",1995-12-22,6.5,92.0,11.7129,"[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]",1995-12-22,6.1,34.0,3.859495,"[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],1995-02-10,5.7,173.0,8.387519,"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug..."

In [ ]:
def fetch_director(obj):

    L = []

    for i in obj:

        if i['job'] == 'Director':

            L.append(i['name'])

            break

    return L

In [ ]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [ ]:
movies[['genres','cast','crew','keywords']].head()

,genres,cast,crew,keywords
0,"[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva..."
1,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'..."
2,"[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],"[fishing, best friend, duringcreditsstinger, o..."
3,"[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],"[based on novel, interracial relationship, sin..."
4,[Comedy],"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer],"[baby, midlife crisis, confidence, aging, daug..."

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [ ]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])

In [ ]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [ ]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [ ]:
movies = movies[['id', 'title', 'tags']]

In [ ]:
movies.drop_duplicates(inplace=True)

In [ ]:
movies.to_csv("processed_movies.csv", index=False)

In [ ]:
print(movies.columns.tolist())

['id', 'title', 'tags']

In [ ]:
print(movies.head())

      id                        title  \
0    862                    Toy Story
1   8844                      Jumanji
2  15602             Grumpier Old Men
3  31357            Waiting to Exhale
4  11862  Father of the Bride Part II

                                                tags
0  Led by Woody, Andy's toys live happily in his ...
1  When siblings Judy and Peter discover an encha...
2  A family wedding reignites the ancient feud be...
3  Cheated on, mistreated and stepped on, the wom...
4  Just when George Banks has recovered from his ...

In [ ]:
metadata = pd.read_csv(
    "../movies_metadata.csv",
    low_memory=False
)

In [ ]:
print(metadata.columns.tolist())

['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count']

In [ ]:
print(
    metadata[
        [
            "id",
            "title",
            "overview",
            "genres",
            "release_date",
            "vote_average",
            "poster_path"
        ]
    ].head()
)

      id                        title  \
0    862                    Toy Story
1   8844                      Jumanji
2  15602             Grumpier Old Men
3  31357            Waiting to Exhale
4  11862  Father of the Bride Part II

                                            overview  \
0  Led by Woody, Andy's toys live happily in his ...
1  When siblings Judy and Peter discover an encha...
2  A family wedding reignites the ancient feud be...
3  Cheated on, mistreated and stepped on, the wom...
4  Just when George Banks has recovered from his ...

                                              genres release_date  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   1995-10-30
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   1995-12-15
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   1995-12-22
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   1995-12-22
4                     [{'id': 35, 'name': 'Comedy'}]   1995-02-10

   vote_average                       poster_path
0           7.7  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1           6.9  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2           6.5  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3           6.1  /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4           5.7  /e64sOI48hQXyru7naBFyssKFxVd.jpg

In [ ]:
print(metadata.columns.tolist())

['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count']

In [ ]:
movie_details = metadata[
    [
        "id",
        "title",
        "overview",
        "genres",
        "release_date",
        "vote_average",
        "vote_count",
        "poster_path"
    ]
].copy()

In [ ]:
print(movie_details.shape)
print(movie_details.head())

(45466, 8)
      id                        title  \
0    862                    Toy Story
1   8844                      Jumanji
2  15602             Grumpier Old Men
3  31357            Waiting to Exhale
4  11862  Father of the Bride Part II

                                            overview  \
0  Led by Woody, Andy's toys live happily in his ...
1  When siblings Judy and Peter discover an encha...
2  A family wedding reignites the ancient feud be...
3  Cheated on, mistreated and stepped on, the wom...
4  Just when George Banks has recovered from his ...

                                              genres release_date  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   1995-10-30
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   1995-12-15
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   1995-12-22
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   1995-12-22
4                     [{'id': 35, 'name': 'Comedy'}]   1995-02-10

   vote_average  vote_count                       poster_path
0           7.7      5415.0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1           6.9      2413.0  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2           6.5        92.0  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3           6.1        34.0  /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4           5.7       173.0  /e64sOI48hQXyru7naBFyssKFxVd.jpg

In [ ]:
movie_details["overview"] = movie_details["overview"].fillna("")

movie_details["release_date"] = movie_details["release_date"].fillna("")

movie_details["vote_average"] = pd.to_numeric(
    movie_details["vote_average"],
    errors="coerce"
).fillna(0)

movie_details["vote_count"] = pd.to_numeric(
    movie_details["vote_count"],
    errors="coerce"
).fillna(0)

movie_details["poster_path"] = movie_details["poster_path"].fillna("")

In [ ]:
movie_details["id"] = pd.to_numeric(
    movie_details["id"],
    errors="coerce"
)

In [ ]:
movie_details = movie_details.dropna(subset=["id"])

In [ ]:
movie_details["id"] = movie_details["id"].astype(int)

In [ ]:
movie_details = movie_details.drop_duplicates(
    subset=["id"]
)

In [ ]:
print(movie_details.shape)

(45433, 8)

In [ ]:
movie_details.to_pickle(
    "../data/movie_details.pkl"
)

In [ ]:
import os

print(
    os.path.getsize("../data/movie_details.pkl") / (1024 ** 2),
    "MB"
)

18.670578956604004 MB

In [ ]:
test_details = pd.read_pickle(
    "../data/movie_details.pkl"
)

print(test_details.columns.tolist())

['id', 'title', 'overview', 'genres', 'release_date', 'vote_average', 'vote_count', 'poster_path']

In [ ]:
print(
    test_details[
        test_details["title"].str.lower() == "toy story"
    ]
)

    id      title                                           overview  \
0  862  Toy Story  Led by Woody, Andy's toys live happily in his ...

                                              genres release_date  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   1995-10-30

   vote_average  vote_count                       poster_path
0           7.7      5415.0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg

In [ ]:
toy = movie_details[
    movie_details["title"].str.lower() == "toy story"
]

print(
    toy[
        ["id", "title", "poster_path"]
    ].to_string(index=False)
)

 id     title                      poster_path
862 Toy Story /rhIRbceoE9lR4veEXuwCC2wARtG.jpg

In [ ]:
toy = movie_details[
    movie_details["title"].str.lower() == "toy story"
]

print(
    toy[
        ["id", "title", "poster_path"]
    ].to_string(index=False)
)

 id     title                      poster_path
862 Toy Story /rhIRbceoE9lR4veEXuwCC2wARtG.jpg

In [ ]:
import requests

poster_path = toy.iloc[0]["poster_path"]

url = f"https://image.tmdb.org/t/p/w500{poster_path}"

response = requests.get(url)

print("URL:", url)
print("Status:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))

ModuleNotFoundError: No module named 'requests'

In [ ]:
print(
    toy[
        ["id", "title", "poster_path"]
    ].to_string(index=False)
)

 id     title                      poster_path
862 Toy Story /rhIRbceoE9lR4veEXuwCC2wARtG.jpg

In [2]:
import pandas as pd

movie_details = pd.read_pickle("../data/movie_details.pkl")

toy = movie_details[
    movie_details["title"].str.lower() == "toy story"
]

print(
    toy[["id", "title", "poster_path"]].to_string(index=False)
)

 id     title                      poster_path
862 Toy Story /rhIRbceoE9lR4veEXuwCC2wARtG.jpg

In [4]:
poster_path = toy.iloc[0]["poster_path"]

url = f"https://image.tmdb.org/t/p/w500{poster_path}"

print(url)

https://image.tmdb.org/t/p/w500/rhIRbceoE9lR4veEXuwCC2wARtG.jpg