## data understanding

In [3]:
import pandas as pd
import numpy as np
import ast

In [4]:
movies = pd.read_csv("../movies_metadata.csv", low_memory=False)

credits = pd.read_csv("../credits.csv")

keywords = pd.read_csv("../keywords.csv")

ratings = pd.read_csv("../ratings_small.csv")

In [5]:
movies.sample(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
25301,False,NaN,20000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.facebook.com/SavingGeneralYang,181009,tt2072220,zh,忠烈楊家將,When a rival nation sends troops to invade the...,...,2013-04-04,0.0,102.0,"[{'iso_639_1': 'zh', 'name': '普通话'}]",Released,NaN,Saving General Yang,False,6.1,44.0
4692,False,NaN,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",NaN,34549,tt0273799,en,Max Keeble's Big Move,"Max Keeble, the victim of his 7th grade class,...",...,2001-10-05,17292381.0,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His World. His Rules.,Max Keeble's Big Move,False,5.4,33.0
27173,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,247447,tt0243218,fa,بید و باد,A boy breaks a window at his school and sets o...,...,2000-01-01,0.0,77.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Willow and Wind,False,10.0,1.0
19930,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,45006,tt0104516,en,Interceptor,A U.S. Air Force officer tries to stop a murde...,...,1992-10-13,0.0,92.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,You can't kill what you can't find.,Interceptor,False,5.6,5.0
35306,False,NaN,0,[],NaN,131897,tt0084079,it,Ho fatto splash,NaN,...,1980-10-30,0.0,0.0,[],Released,NaN,I Made a Splash,False,6.7,3.0

In [6]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  str
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(1), str(19)
memory usage: 8.3+ MB

In [7]:
movies.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [8]:
movies = movies[
    [
        "id",
        "title",
        "overview",
        "genres",
        "release_date",
        "vote_average",
        "vote_count",
        "popularity"
    ]
]

In [9]:
movies = movies.dropna(subset=["overview"])

In [10]:
movies = movies.fillna("")

In [11]:
movies = movies[pd.to_numeric(movies["id"], errors="coerce").notnull()]

movies["id"] = movies["id"].astype(int)

In [12]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [13]:
credits["id"] = credits["id"].astype(int)

In [14]:
keywords["id"] = keywords["id"].astype(int)

In [15]:
movies = movies.merge(credits, on="id")

movies = movies.merge(keywords, on="id")

In [16]:
movies["genres"] = movies["genres"].apply(ast.literal_eval)

movies["cast"] = movies["cast"].apply(ast.literal_eval)

movies["crew"] = movies["crew"].apply(ast.literal_eval)

movies["keywords"] = movies["keywords"].apply(ast.literal_eval)

In [17]:
movies.head()

,id,title,overview,genres,release_date,vote_average,vote_count,popularity,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",1995-10-30,7.7,5415.0,21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",1995-12-15,6.9,2413.0,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",1995-12-22,6.5,92.0,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-12-22,6.1,34.0,3.859495,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",1995-02-10,5.7,173.0,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [18]:
def convert(obj):
    L = []

    for i in obj:
        L.append(i['name'])

    return L

In [19]:
movies['genres'] = movies['genres'].apply(convert)

In [20]:
movies.head()

,id,title,overview,genres,release_date,vote_average,vote_count,popularity,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]",1995-10-30,7.7,5415.0,21.946943,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]",1995-12-15,6.9,2413.0,17.015539,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]",1995-12-22,6.5,92.0,11.7129,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]",1995-12-22,6.1,34.0,3.859495,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],1995-02-10,5.7,173.0,8.387519,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [21]:
movies['keywords'] = movies['keywords'].apply(convert)

In [22]:
def convert_cast(obj):

    L = []

    counter = 0

    for i in obj:

        if counter != 3:

            L.append(i['name'])

            counter += 1

        else:

            break

    return L


movies['cast'] = movies['cast'].apply(convert_cast)

In [23]:
movies.head()

,id,title,overview,genres,release_date,vote_average,vote_count,popularity,cast,crew,keywords
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]",1995-10-30,7.7,5415.0,21.946943,"[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]",1995-12-15,6.9,2413.0,17.015539,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'..."
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Romance, Comedy]",1995-12-22,6.5,92.0,11.7129,"[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o..."
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]",1995-12-22,6.1,34.0,3.859495,"[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,[Comedy],1995-02-10,5.7,173.0,8.387519,"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug..."

In [27]:
def fetch_director(obj):

    L = []

    for i in obj:

        if i['job'] == 'Director':

            L.append(i['name'])

            break

    return L

In [28]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [29]:
movies[['genres','cast','crew','keywords']].head()

,genres,cast,crew,keywords
0,"[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva..."
1,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'..."
2,"[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],"[fishing, best friend, duringcreditsstinger, o..."
3,"[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],"[based on novel, interracial relationship, sin..."
4,[Comedy],"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer],"[baby, midlife crisis, confidence, aging, daug..."

In [30]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [31]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])

In [32]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [33]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [34]:
movies = movies[['id', 'title', 'tags']]

In [35]:
movies.drop_duplicates(inplace=True)

In [36]:
movies.to_csv("processed_movies.csv", index=False)